repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      # - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key

  # Python specific hooks
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: "backend/.*\\.py$"

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        files: "backend/.*\\.py$"

  # - repo: https://github.com/charliermarsh/ruff-pre-commit
  #   rev: v0.0.262
  #   hooks:
  #     - id: ruff
  #       files: "backend/.*\\.py$"
  #       args: [--fix, --exit-non-zero-on-fix]

  # JavaScript/TypeScript specific hooks
  # TODO: Fix compat issues
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v9.3.0
  #   hooks:
  #     - id: eslint
  #       files: "frontend/.*\\.(js|jsx|ts|tsx)$"
  #       types: [file]
  #       args: ["--config", "frontend/eslint.config.mjs"]
  #       additional_dependencies:
  #         - eslint@9.3.0
  #         - "@eslint/js@9.3.0"
  #         - eslint-plugin-react@7.32.2
  #         - eslint-config-next@13.3.0
  #         - typescript@5.0.4
  #         - "@typescript-eslint/eslint-plugin@5.59.0"
  #         - "@typescript-eslint/parser@5.59.0"
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'cd frontend && npx eslint "src/**/*.{js,jsx,ts,tsx}" --config eslint.config.mjs'
        language: system
        files: "frontend/src/.*\\.(js|jsx|ts|tsx)$"
        types: [file]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        files: "frontend/.*\\.(js|jsx|ts|tsx|css|md|json)$"
        exclude: "package-lock.json|yarn.lock"
